#!/usr/bin/env python3
"""
preflight.py — diagnostic characterisation of all real-world .bin datasets.

Computes per-file:
  - n_values, min, max, mean, stdev, geometric mean (positives only)
  - n_zeros, n_negatives, n_nan, n_inf
  - distribution of |log2(x_{t+1}) - log2(x_t)| (log-step magnitudes)
  - max log-step (predicts LNS saturation risk; threshold: >0.7 for saturation)
  - n_suspected_splits: single-step |change| > 40% (unadjusted split detection)

Writes data/PREFLIGHT.md.
"""
import sys
import math
from pathlib import Path
import struct

try:
    import numpy as np
except ImportError:
    print("numpy required: pip install numpy"); sys.exit(1)

ROOT = Path(__file__).parent.parent
DATA_DIRS = [
    ROOT / "data" / "yfinance",
    ROOT / "data" / "yfinance_1m",
    ROOT / "data" / "sdrbench",
]

def load_bin(path):
    data = path.read_bytes()
    n = len(data) // 8
    return np.frombuffer(data[:n*8], dtype='<f8').copy()

def analyse(arr, name):
    n = len(arr)
    n_nan  = int(np.sum(np.isnan(arr)))
    n_inf  = int(np.sum(np.isinf(arr)))
    finite = arr[np.isfinite(arr)]
    n_zero = int(np.sum(finite == 0.0))
    n_neg  = int(np.sum(finite < 0.0))
    pos    = finite[finite > 0.0]

    if len(finite) == 0:
        return {"name": name, "n": n, "error": "no finite values"}

    vmin  = float(np.min(finite))
    vmax  = float(np.max(finite))
    mean  = float(np.mean(finite))
    stdev = float(np.std(finite, ddof=1)) if len(finite) > 1 else 0.0
    geom_mean = float(np.exp(np.mean(np.log(pos)))) if len(pos) > 0 else float('nan')

    # Log-step magnitudes (on consecutive positive values only)
    log_steps = []
    max_log_step = float('nan')
    n_splits = 0
    if len(pos) >= 2:
        # Use the original array order for consecutive steps
        # Filter out non-finite and non-positive consecutively
        valid_mask = (np.isfinite(arr)) & (arr > 0.0)
        valid_vals = arr[valid_mask]
        if len(valid_vals) >= 2:
            log_vals  = np.log2(valid_vals)
            log_diffs = np.abs(np.diff(log_vals))
            max_log_step = float(np.max(log_diffs))
            # Percentiles
            p25, p50, p75, p95 = np.percentile(log_diffs, [25, 50, 75, 95])

            # Suspected splits: >40% single-day absolute change (on raw prices)
            pct_changes = np.abs(np.diff(valid_vals) / valid_vals[:-1])
            n_splits = int(np.sum(pct_changes > 0.40))

            log_steps = {"p25": float(p25), "p50": float(p50),
                         "p75": float(p75), "p95": float(p95),
                         "max": max_log_step}

    return {
        "name": name, "n": n,
        "min": vmin, "max": vmax, "mean": mean, "stdev": stdev, "geom_mean": geom_mean,
        "n_zero": n_zero, "n_neg": n_neg, "n_nan": n_nan, "n_inf": n_inf,
        "log_steps": log_steps,
        "max_log_step": max_log_step,
        "n_suspected_splits": n_splits,
    }

def format_oneliner(d):
    if "error" in d:
        return f"{d['name']}: ERROR — {d['error']}"
    ls = d.get("log_steps", {})
    max_ls = f"{d['max_log_step']:.4f}" if not math.isnan(d.get('max_log_step', float('nan'))) else "n/a"
    median_ls = f"{ls.get('p50', float('nan')):.4f}" if ls else "n/a"
    return (
        f"{d['name']}: {d['n']} values, "
        f"range [{d['min']:.4g}, {d['max']:.4g}], "
        f"mean {d['mean']:.4g}, stdev {d['stdev']:.4g}, "
        f"median_log_step {median_ls}, max_log_step {max_ls}, "
        f"{d['n_zero']} zeros, {d['n_neg']} negatives, "
        f"{d.get('n_suspected_splits',0)} suspected_splits"
    )

results = []
for data_dir in DATA_DIRS:
    if not data_dir.exists():
        continue
    for f in sorted(data_dir.glob("*.bin")):
        arr = load_bin(f)
        d = analyse(arr, f.stem)
        results.append(d)
        print(format_oneliner(d))

# Write PREFLIGHT.md
out_path = ROOT / "data" / "PREFLIGHT.md"
with open(out_path, "w") as fh:
    fh.write("# Diagnostic Preflight Report\n\n")
    fh.write("Generated by `tools/preflight.py` before running compression benchmarks.\n\n")
    fh.write("**Saturation risk threshold:** max_log_step > 0.693 (log2(1.618)) means a single step\n")
    fh.write("exceeds 61.8% ratio change — likely causes LNS saturation for Q8.24.\n\n")
    fh.write("**Split detection threshold:** single-day |pct_change| > 40% flagged as suspected split.\n")
    fh.write("These should be absent if auto_adjust=True was used in yfinance.\n\n")
    fh.write("---\n\n")

    # Group by directory
    daily  = [r for r in results if "yfinance" in str(r.get("name","")) and "_1m" not in str(r.get("name",""))]
    intra  = [r for r in results if "yfinance_1m" in str(r.get("name",""))]
    sci    = [r for r in results if r not in daily and r not in intra]

    # Actually group by checking presence in which dir
    # Re-sort by origin
    daily_names  = set()
    intra_names  = set()
    sci_names    = set()
    for data_dir in DATA_DIRS:
        if not data_dir.exists():
            continue
        for f in sorted(data_dir.glob("*.bin")):
            if "yfinance_1m" in str(data_dir):
                intra_names.add(f.stem)
            elif "yfinance" in str(data_dir):
                daily_names.add(f.stem)
            else:
                sci_names.add(f.stem)

    fh.write("## Daily OHLCV (data/yfinance/)\n\n")
    fh.write("| Dataset | N | Min | Max | Mean | Stdev | Median LogStep | Max LogStep | Zeros | Negatives | Susp.Splits |\n")
    fh.write("|---------|---|-----|-----|------|-------|----------------|-------------|-------|-----------|-------------|\n")
    for r in results:
        if r["name"] not in daily_names: continue
        ls = r.get("log_steps", {})
        mls = f"{r.get('max_log_step', float('nan')):.4f}" if not math.isnan(r.get('max_log_step', float('nan'))) else "n/a"
        med = f"{ls.get('p50', float('nan')):.4f}" if ls else "n/a"
        fh.write(f"| {r['name']} | {r['n']:,} | {r['min']:.4g} | {r['max']:.4g} | {r['mean']:.4g} | {r['stdev']:.4g} | {med} | {mls} | {r['n_zero']} | {r['n_neg']} | {r.get('n_suspected_splits',0)} |\n")

    fh.write("\n## Intraday 1-min (data/yfinance_1m/)\n\n")
    fh.write("| Dataset | N | Min | Max | Mean | Stdev | Median LogStep | Max LogStep | Zeros | Negatives | Susp.Splits |\n")
    fh.write("|---------|---|-----|-----|------|-------|----------------|-------------|-------|-----------|-------------|\n")
    for r in results:
        if r["name"] not in intra_names: continue
        ls = r.get("log_steps", {})
        mls = f"{r.get('max_log_step', float('nan')):.4f}" if not math.isnan(r.get('max_log_step', float('nan'))) else "n/a"
        med = f"{ls.get('p50', float('nan')):.4f}" if ls else "n/a"
        fh.write(f"| {r['name']} | {r['n']:,} | {r['min']:.4g} | {r['max']:.4g} | {r['mean']:.4g} | {r['stdev']:.4g} | {med} | {mls} | {r['n_zero']} | {r['n_neg']} | {r.get('n_suspected_splits',0)} |\n")

    if any(r["name"] in sci_names for r in results):
        fh.write("\n## Scientific Data (data/sdrbench/)\n\n")
        fh.write("| Dataset | N | Min | Max | Mean | Stdev | Median LogStep | Max LogStep | Zeros | Negatives | Susp.Splits |\n")
        fh.write("|---------|---|-----|-----|------|-------|----------------|-------------|-------|-----------|-------------|\n")
        for r in results:
            if r["name"] not in sci_names: continue
            ls = r.get("log_steps", {})
            mls = f"{r.get('max_log_step', float('nan')):.4f}" if not math.isnan(r.get('max_log_step', float('nan'))) else "n/a"
            med = f"{ls.get('p50', float('nan')):.4f}" if ls else "n/a"
            fh.write(f"| {r['name']} | {r['n']:,} | {r['min']:.4g} | {r['max']:.4g} | {r['mean']:.4g} | {r['stdev']:.4g} | {med} | {mls} | {r['n_zero']} | {r['n_neg']} | {r.get('n_suspected_splits',0)} |\n")
    else:
        fh.write("\n## Scientific Data (data/sdrbench/)\n\nNo SDR-Bench .bin files found (download failed or not yet extracted).\n")

    fh.write("\n---\n\n### One-liner Summary\n\n```\n")
    for r in results:
        fh.write(format_oneliner(r) + "\n")
    fh.write("```\n")

print(f"\nWrote {out_path}")
